version: 0.0
    os: linux
    files:
      - source: target/airline-app.jar
        destination: /home/ubuntu/
    hooks:
      ApplicationStop:
        - location: scripts/stop_application.sh
          timeout: 300
      BeforeInstall:
        - location: scripts/install_dependencies.sh
          timeout: 300
      ApplicationStart:
        - location: scripts/start_application.sh
          timeout: 300
